name: Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run:
        docker login --username omisegobot --password ${{ secrets.OMGBOT_DOCKER_TOKEN }}
    - name: Docker Build & Publish
      run: |
        GIT_COMMIT_SHA=$(git rev-parse --short=7 HEAD)
        GIT_SHA_TAG=omisego/spinnaker-pipeline-artifact:$GIT_COMMIT_SHA
        LATEST_TAG=omisego/spinnaker-pipeline-artifact:latest

        docker build --file Dockerfile -t spinnaker-pipeline .
        docker tag spinnaker-pipeline $GIT_SHA_TAG $LATEST_TAG
        docker push omisego/spinnaker-pipeline-artifact
